/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jorge
 */
public class Tabla extends javax.swing.JPanel {
    
    JTable tabla = new JTable();
    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
        tabla.getModel().removeTableModelListener(tabla);
        setModel(
            new String [][] {
                {"Title 1", "Title 2"},
                {"Title 1", "Title 2"}
            }, new String [] {
                "Jugador 1", "Jugador 2"
            });
        tabla.setSize(100, 200);
        tabla.getSelectionModel().removeListSelectionListener(tabla);
        this.add(tabla);
    }

    public void setModel(Object[][] datos, Object[] titulos) {
        tabla.setModel(new DefaultTableModel(datos, titulos));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
