/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tablero;

/**
 *
 * @author jorge
 */
public class TablaInvertida extends javax.swing.JFrame {
    private static boolean SENTIDO = false;
    Tabla tablaInvertida = new Tabla();
    Tabl framePrincipal;
    String idioma;

    public String getIdioma() {
        return idioma;
    }

    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    
    /**
     * Creates new form TablaInvertida
     */
    public TablaInvertida(Tabl framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        setIdioma((String)jComboBox1.getSelectedItem());
        setTitle("Tabla Invertida");
        setLocation(800, 500);
        tablaInvertida.getTabla().addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        this.add(tablaInvertida.getTabla());
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        limpiar();
        framePrincipal.limpiarTableroNormal();
        System.err.println("J1: ");
        framePrincipal.setContador1((int) tablaInvertida.getTabla().getValueAt(0, tablaInvertida.getTabla().getSelectedRow()));
        framePrincipal.setContador2((int) tablaInvertida.getTabla().getValueAt(1, tablaInvertida.getTabla().getSelectedRow()));
    }
    
    public void limpiar() {
        tablaInvertida.limpiaTabla(tablaInvertida.getTabla().getSelectedRow(),SENTIDO);
    }
        
    public void agregaFila(int ptn1, int ptn2, String score) {
        tablaInvertida.generaTabla(ptn1, ptn2, score, this.SENTIDO);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Español", "Ingles", "Frances" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 267, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        setIdioma((String)jComboBox1.getSelectedItem());
        System.out.println(jComboBox1.getSelectedItem());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaInvertida(new Tabl()).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
}
