/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tablero;

/**
 *
 * @author jorge
 */
public class TablaInvertida extends javax.swing.JFrame {
    private static boolean SENTIDO = false;
    Tabla tablaInvertida = new Tabla();
    Tabl framePrincipal;
    /**
     * Creates new form TablaInvertida
     */
    public TablaInvertida(Tabl framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        setTitle("Tabla Invertida");
        setLocation(800, 500);
        tablaInvertida.getTabla().addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        this.add(tablaInvertida.getTabla());
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        limpiar();
        framePrincipal.limpiarTableroNormal();
        System.err.println("J1: ");
        framePrincipal.setContador1((int) tablaInvertida.getTabla().getValueAt(0, tablaInvertida.getTabla().getSelectedRow()));
        framePrincipal.setContador2((int) tablaInvertida.getTabla().getValueAt(1, tablaInvertida.getTabla().getSelectedRow()));
    }
    
    public void limpiar() {
        tablaInvertida.limpiaTabla(tablaInvertida.getTabla().getSelectedRow(),SENTIDO);
    }
        
    public void agregaFila(int ptn1, int ptn2, String score) {
        tablaInvertida.generaTabla(ptn1, ptn2, score, this.SENTIDO);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaInvertida(new Tabl()).setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
